pipelines:
  branches:
    master:
      - step:
          name: Build and test the app
          image: node:latest
          script:
            - npm install
            - unset CI
            - npm run build
